### ISSUE TITLE
requirements.txt and commands

### ISSUE THREAD

**Issue by hhhyyeee** [RyanKim17920/DeepMoE#1]
Hi! Thanks for your hard work in this project.

Can you please provide any information to reproduce your results in our work environment?
The information may include requirements.txt or CLI python commands.

Thanks!

**Comment by RyanKim17920** [comment]
Hi,
Thanks for the feedback. I haven't looked at this project for months so it might take me around a week to organize it further.

**Comment by RyanKim17920** [comment]
I've updated the code accordingly.
